### ISSUE TITLE
Failing a ref.once call

### ISSUE THREAD

**Issue by jQrgen** [soumak77/firebase-mock#10]
Hello

It would be nice to be able to cause ref.once call to fail. I'm currently calling 
```
this.somefunction = function(){
    ref.child('/phone_numbers/' + phone).once(...) 
}
```
in an angular controller and in my test code(jasmine) the following code does not cause the ref.once call to fail:
```
ctrl.firebaseRef.failNext('update', error);
ctrl.somefunction();
ctrl.firebaseRef.flush();
```

Thus I want ref.once() to fail and return an error in the callback so that I can throw an error and catch it in my test.

I would implement it into the library myself but I'm a beginner in unit testing & mocking and I cant seem to figure out how this mock library works so that I can extend it. 

A new feature or a guidance on how I could implement it myself would be awesome.

JQ

**Comment by soumak77** [comment]
@jQrgen Not sure if this would work, but have you tried changing `update` to `once` in the `failNext` call?

**Comment by jQrgen** [comment]
Thanks! This worked:

Angular controller:
```
 $scope.submitNumber = function(phone, country){
   that.firebaseRef.child('/phone_numbers/' + phone).once('value', function(snap){
       that.checkIfNumberExists(snap, phone, selectedCountryObject);
     }, (error) => {
       if(error){
         throw error;
       }
   });
 };   
```

Jasmine:

```
    function submitNumber(){
      var error = new Error('asdasd');
      ctrl.firebaseRef.child('/phone_numbers/' + '+190080822').failNext('once', error);
      $scope.submitNumber('90080822', simPluginDataNO);
      ctrl.firebaseRef.flush();
    }
    expect(submitNumber).toThrowError("asdasd");
```
