### ISSUE TITLE
Question: How to define sub-collections of documents when defining MockFirestore?

### ISSUE THREAD

**Issue by ilearnio** [soumak77/firebase-mock#103]
Currently we define mocked DB documents like so:

```ts
const db = new MockFirestore(null, {
  collectionName: {
    documentId: {
      name: 'foo',
      createdAt: new Date(0),
    },
    ...
  }
})
```

Is there any way to pass nested sub-collections? So it would look something like:

```ts
const db = new MockFirestore(null, {
  collectionName: {
    documentId: {
      name: 'foo',
      createdAt: new Date(0),
      
      subCollections: { // <-- Need to do something like this
        subCollectionName: {
          documentId: {
            ...
          }
        },
        ...
      }
    }
  }
})
```

**Comment by soumak77** [comment]
@ilearnio your example is not the desired way to initialize documents.  You should use the firestore API when needing to initialize any data.  This is true for documents and collections.  Please read the [tutorial](https://github.com/soumak77/firebase-mock/blob/master/tutorials/client/firestore.md) for more info or check out some of the unit tests in this library to see how they initialize data.
