### ISSUE TITLE
Mocking ref.update

### ISSUE THREAD

**Issue by jQrgen** [soumak77/firebase-mock#12]
Hello

I'm trying to mock a ref.update function but it does not seem to work. 
is ref.update() a part of the library? 
Where can I see what methods are implemented in the library or not? I would love to extend it.

Code (Angular controller):
```   
this.userRef = null;
    this.user = {
      ref: function (uid) {
        if (!that.userRef) that.userRef = firebase.database().ref().child('users/' + uid);
        return that.userRef;
      },
      update: function () {
        return that.user.ref("asdasdsdasd").update({
          phone: false,
          verification_code: false,
          country: false
        }, function (error){
          console.log("lol");
          if(error){
            throw error;
          }
        });
      }
    };
```

Jasmine test:
```
    MockFirebase.override();

    var userRef = ctrl.user.update("FAKEID");
    userRef.flush(); //  throws: TypeError: Cannot read property 'flush' of undefined
```

Thanks for any help.

**Comment by soumak77** [comment]
`update` returns a promise, not a reference.  Try the following:

```
var userRef = ctrl.user;
var promise = userRef.update("FAKEID");
userRef.flush();
// promise should be resolved at this point
```

**Comment by jQrgen** [comment]
Appreciate the answer soumak.

The old problem with the original code was that I was trying to flush on a promise. I have implemented the pattern you suggested below. flush() now runs with no errors (I was flushing on the wrong variable).

The new problem is that the promise is still undefined both before and after I have flushed.

Angular controller:
```
    this.userRef = null;
    this.user = {
      ref: function () {
        if (!that.userRef) that.userRef = firebase.database().ref().child('users/asdasdsdasd');
        return that.userRef;
      },
      update: function () {
        return that.user.ref().update({
          phone: false,
          verification_code: false,
          country: false
        }, function (error){
          if(error){
            throw error;
          }
        });
      }
    };

```

Jasmine:
```
    MockFirebase.override();
    var promise = ctrl.user.update();
    console.log(typeof promise); // Undefined
    ctrl.userRef.flush();
    console.log(promise.key());  // Undefined
```
--- >     TypeError: Cannot read property 'key' of undefined

Thanks!!
JQ

**Comment by soumak77** [comment]
It appears the [mock for update](https://github.com/soumak77/firebase-mock/blob/a0364db779489d3a6d6f62f416d7e4d50ccc172e/src/firebase.js#L167-L178) doesn't return a promise.  It must be updated to reflect the [3.0 API](https://firebase.google.com/docs/reference/js/firebase.database.Reference#update).  Until this change is made, you'll have to use the old API.
