### ISSUE TITLE
createUserWithEmailAndPassword not working with v3?

### ISSUE THREAD

**Issue by jQrgen** [soumak77/firebase-mock#15]
Hello

The pattern in [the authentication tutorial](https://github.com/soumak77/firebase-mock/blob/docs/tutorials/authentication.m): is using a deprecated firebase v2  call`Firebase('https://example.firebaseio.com');` instead of v3  `firebase.auth() from v3(;`. Currently using firebase v3 crashes my test. 

```
✖ 1 test failed

FAILED TESTS:
  AlarmButtonEvents
    ✖ Should init authdata
      Chrome 56.0.2924 (Linux 0.0.0)
    TypeError: Cannot read property 'createUserWithEmailAndPassword' of undefined
        at Object.create (http://localhost:1337www/services/firebase.service.js:14:20)
        at Object.<anonymous> (http://localhost:1337www/app/alarmbutton/alarmbutton.events.factory.spec.js:42:25)
```

How users are created in the client:
```js

.service('firebaseService', function() {
     var that = this;

     this.users = {
     	ref: function () {
     		firebase.auth();
	},
     create: function (credentials) {
	that.users.ref().createUserWithEmailAndPassword(credentials).catch(function(error) {
		// Handle Errors here.
		var errorCode = error.code;
		 var errorMessage = error.message;
		// ...
		});
	}
     };
});
```

unit test:

```js
it('Should init authdata', function(){
	MockFirebase.override();
	firebaseService.users.ref();
	firebaseService.users.create({
		email: 'ben@example.com',
		password: 'examplePass'
	});
	firebaseService.flush();
	console.assert(firebaseService.getEmailUser('ben@example.com'), 'ben was created');
});

```

**Comment by soumak77** [comment]
Here are some working examples for authentication unit tests using providers: https://github.com/base-apps/angular-firebase-template/blob/master/app/modules/account/account.spec.js

You'll see in the code that I setup a listener for auth state changes which get triggered after the flush operation.  Creating a user with email/password should work as well using the same structure.

**Comment by jQrgen** [comment]
Thanks, ill give it a shot.

**Comment by soumak77** [comment]
@jQrgen I added support for `createUserWithEmailAndPassword` in version `1.1.4`
