### ISSUE TITLE
Tutorial outdated + initializeApp() mock needed

### ISSUE THREAD

**Issue by jQrgen** [soumak77/firebase-mock#16]
Hello

I'm trying to implement the [tutorial](https://github.com/soumak77/firebase-mock/blob/master/tutorials/proxyquire.md) for overriding `require('firebase')` on a node server using firebase API v3. I get the following message when `ref.on('value', function (snapshot) {` is executed:
```
[DEFAULT]: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).
    at M (/home/jorgen/flareserver/node_modules/firebase/app-node.js:28:397)
    at a (/home/jorgen/flareserver/node_modules/firebase/app-node.js:26:68)
    at Function.c [as database] (/home/jorgen/flareserver/node_modules/firebase/app-node.js:27:492)
    at Object.<anonymous> (/home/jorgen/flareserver/mySrc.js:3:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) (/home/jorgen/flareserver/node_modules/proxyquire/lib/proxyquire.js:276:43)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```
Looking at the firebase-mock library there seems to be no override/mock for the [initializeApp() function](https://firebase.google.com/docs/reference/js/firebase#.initializeApp) used to initialize the firebase lib on node.js servers.
##### My current implementation:
```js
// ./mySrc.js:
var firebaseApp = require('firebase');

var ref = firebaseApp.database().ref();
ref.on('value', function (snapshot) {
	console.log(snapshot.val());
});
```
```js
// ./test.js
var proxyquire   = require('proxyquire');
var MockFirebase = require('firebase-mock').MockFirebase;
var mock;

var mySrc = proxyquire('./mySrc', {
	firebase: function (url) {
		mock = new MockFirebase(url);
		console.log(mock);
		return mock;
	}
});

mock.flush();
// data is logged
```

Thanks
JQ

**Comment by soumak77** [comment]
The V3 fixes for this library to work on node are likely similar to those required to make the library work in the browser.  The following lines were added to support the V3 API: https://github.com/soumak77/firebase-mock/blob/master/helpers/globals.js#L7-L23.

In the code sample above, the `database` and `auth` methods are mocked.  You'll likely need to add a mock for `initializeApp` which is just an empty function call.  This mock object should be returned in your `proxyquire` call.

If you aren't able to get that working, you can look into using [firebase-server](https://github.com/urish/firebase-server) instead for testing.  I used this for writing the test suite for https://github.com/greenhousegames/firebase-reporting.

**Comment by soumak77** [comment]
@jQrgen If you get this working please submit a PR.  The `src/index.js` file for this project should be updated to export a new `MockFirebaseSdk` object which is similar to the one created in `helpers/globals.js`.

**Comment by soumak77** [comment]
Once this is added to `index.js`, `globals.js` can be updated to have a single line:

```
window.MockFirebaseSdk = window.firebasemock.MockFirebaseSdk;
```

**Comment by soumak77** [comment]
@jQrgen I've updated the tutorial for [v3 node support](https://github.com/soumak77/firebase-mock/blob/master/tutorials/proxyquire.md)
