### ISSUE TITLE
Move browserify from `dependencies` to `devDependencies`

### ISSUE THREAD

**Issue by joshlory** [soumak77/firebase-mock#17]
These are causing our project to pull in an older version of uglify-js.  We will update our yarn.lock but it would be helpful if these were moved to `devDependencies`:

https://github.com/soumak77/firebase-mock/blob/72ff5d7a38d9b994eaee5eec423becdf65dfa86d/package.json#L32-L33

**Comment by soumak77** [comment]
resolved with #18
