### ISSUE TITLE
example using webpack

### ISSUE THREAD

**Issue by chrisbraddock** [soumak77/firebase-mock#2]
I'd **really** like to be using this mock but I'm struggling getting it integrated.

I've started my project using the [Vue.js webpack template](https://github.com/vuejs-templates/webpack/tree/master/template) which employs `isparta` as well.

**Comment by soumak77** [comment]
I haven't tried to integrate with webpack yet, so I can't be of immediate help.  I have integrated with brunch ([see project template](https://github.com/base-apps/angular-firebase-template)) which might help you out a bit.  The `firebase-mock` files should be ignored by your app build and just included during testing ([see karma config](https://github.com/base-apps/angular-firebase-template/blob/master/karma.conf.js)).  In your test just use the `window` reference to gain access to the mocks ([see example](https://github.com/base-apps/angular-firebase-template/blob/master/app/modules/account/account.spec.js#L14)).

I just started down the angular 2 path, which uses webpack, so at some point I'll figure it out.

**Comment by chrisbraddock** [comment]
I'm going to have to mess with it again when I can dedicate some time. I've burned a lot already. I'm still learning Webpack so I'm highly disadvantaged.

I reverted to using stubs (Sinon) and crossing my fingers for now. I'm afraid I'm going to have to put in more of the work that you've done in your mock though as I keep writing more tests. We'll see. 

Thanks

**Comment by soumak77** [comment]
Using spies/stubs is a great alternative for small projects, however, as you mentioned, you'll end up doing a lot more work if you use that technique for large projects.

**Comment by soumak77** [comment]
@chrisbraddock I've updated this library to work with node (https://github.com/soumak77/firebase-mock/blob/master/tutorials/proxyquire.md).  Let me know if this helps with webpack integration.

**Comment by chrisbraddock** [comment]
@soumak77 I appreciate the efforts. Unfortunately I abandoned my attempts to setup testing against Firebase and probably won't be revisiting this any time soon. Maybe someone else will come along with the same issue, otherwise I'd say close it up if you've had success. Thanks!
