### ISSUE TITLE
Database reference

### ISSUE THREAD

**Issue by oddui** [soumak77/firebase-mock#3]
Hi, is there plan to support the new [firebase.database().ref()](https://firebase.google.com/support/guides/firebase-web#get_a_database_reference_numbered) interface? Thanks

**Comment by soumak77** [comment]
Yes, in fact I implemented it in my original mockfirebase PR (https://github.com/katowulf/mockfirebase/pull/112), but looks like I never transferred that code to this repo.

**Comment by oddui** [comment]
Thank you!

I'll try it out.

**Comment by soumak77** [comment]
Available as part of [1.0.2](https://github.com/soumak77/firebase-mock/releases/tag/v1.0.2)

**Comment by soumak77** [comment]
Forgot to update some changes from my PR.  1.0.2 is broken and will be fixed with 1.0.3 shortly.

**Comment by oddui** [comment]
Unfortunately it does not seem to work for me. This is how i use it:

```
import { MockFirebase } from 'firebase-mock';

let firebase;

beforeAll(() => firebase = new MockFirebase());

it('fails', () => {
  expect(firebase.database).toBeDefined();
});
```

**Comment by soumak77** [comment]
You can check out this [project template](https://github.com/base-apps/angular-firebase-template) which uses `firebase-mock`.  I'm updating it right now to use the latest version.
