### ISSUE TITLE
firebase.auth.GithubAuthProvider.credential Error

### ISSUE THREAD

**Issue by angeliski** [soumak77/firebase-mock#32]
My test is about generate a new Github credential, but when I run, I got the error:
**TypeError: firebase.auth.GithubAuthProvider.credential is not a function**
I believe that error is because the sdk.js return a function:
**MockFirebaseAuth.GithubAuthProvider = function ...**
If I change that file to use a JSON Object I get the expected result...

I use that because I need call after the **signInWithCredential**, but I can test that signin now.
It's needed change the code in any PR or I can make something for evict that way?

**Comment by soumak77** [comment]
@angeliski A `credential` method will need to be added to the provider to support your use case.  The method should be added here: https://github.com/soumak77/firebase-mock/blob/master/src/sdk.js#L21

**Comment by soumak77** [comment]
@angeliski are you referring to this method?

https://firebase.google.com/docs/reference/android/com/google/firebase/auth/GithubAuthProvider.html#getCredential(java.lang.String)

**Comment by soumak77** [comment]
Disregard that last comment.  The link I sent was for the android SDK.  I see the `credential` method for the web sdk.

https://firebase.google.com/docs/reference/js/firebase.auth.GithubAuthProvider

**Comment by angeliski** [comment]
@soumak77  Is the JS sdk. But I try added a new method inside GithubAuthProvider, but doesn't work.
I use that documentation in my develop: https://firebase.google.com/docs/auth/web/github-auth#processe_o_fluxo_de_login_manualmente
`var credential = firebase.auth.GithubAuthProvider.credential(token);`

The problem is, I don't call GithubAuthProvider how a function, I call the property credential from GithubAuthProvider.

**Comment by soumak77** [comment]
@angeliski understood, I'm refactoring the code now

**Comment by soumak77** [comment]
@angeliski support for credential method has been added to v1.1.5

**Comment by angeliski** [comment]
Amazing @soumak77 ! I install and work! Great Job!
