### ISSUE TITLE
Mock FirebaseUser

### ISSUE THREAD

**Issue by joelwross** [soumak77/firebase-mock#38]
Thanks for this great library! One piece that is missing is a set of mocks around the [FirebaseUser](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseUser) class, (which is passed in to the `onAuthStateChanged()` callback). I'm trying to test that use of helper methods (e.g., `updateProfile()`) are working correctly, but since currently the returned firebase user is just a plain object, this functionality isn't available.

**Comment by soumak77** [comment]
@joelwross I have added a mock user object with basic functionality
