### ISSUE TITLE
Auth error mock

### ISSUE THREAD

**Issue by TarikHuber** [soumak77/firebase-mock#47]
Hi,

Is it possible to simulate an auth error even?
Didn't find anything in the docu about that.

Thx

**Comment by soumak77** [comment]
You should be able to pass any of the auth methods to `failNext` to have that method error on next call.  The list of auth methods can be found here: https://github.com/soumak77/firebase-mock/blob/master/src/auth.js#L75-L80

**Comment by TarikHuber** [comment]
Thx @soumak77 . Will try it ASAP. I'm working on a library to sync firebase with redux: https://github.com/TarikHuber/firekit It has no dependencies and only functional programming. I'm trying to get the tests to 100% (status now 90%). A feedback from you would be awesome 😄

**Comment by soumak77** [comment]
@TarikHuber have you checked out https://github.com/firebase/reactfire?  That might help

**Comment by TarikHuber** [comment]
Thx @soumak77 for the suggestion. I know that project. It is unfortunately very component based. Some project use redux as single state of truth so a redux sync is required. It also enables sync that is not limited by a component and firekit is in that sense the only library that supports persistent sync.

**Comment by soumak77** [comment]
closing as resolved
