### ISSUE TITLE
Question on using Database as the origin of data.

### ISSUE THREAD

**Issue by mpontus** [soumak77/firebase-mock#48]
Hi, I would like to ask why are updates recorded on Reference level and not on Database level?

I think it might be useful if you could pass a database as a function argument and then flush updates to multiple refs simultaneously.

Do you agree? Is this an approach that `firebase-mock` could adopt in the future?

**Comment by soumak77** [comment]
All child refs should update when flushing changing to a parent ref so your use case should be supported.

```
var firebasemock    = require('firebase-mock');
var mockfirebase    = new firebasemock.MockFirebase();
var mockfirestore   = new firebasemock.MockFirestore();

mockfirebase.flush(); // flushes real-time database
mockfirestore.flush(); // flushes firestore database
```

**Comment by mpontus** [comment]
Thank you for your reply, @soumak77.

Consider the following function:

```
const createUser = (database, id) => {
  database.ref(`/users/all/${id}`).set(1);
  database.ref(`/users/active/${id}`).set(1);
};
```

Testing the above function would look something like this:

```
const mockDatabase = {
  allUsersRef: new MockFirebase(),
  activeUsersRef: new MockFirebase(),
  ref: path => {
    switch (path) {
      case `/users/all/${userId}`:
        return this.allUsersRef;
      case `/users/active/${userId}`:
        return this.activeUsersRef;
      default:
        throw new Error(`Unexpeted ref: ${path}`);
    }
  },
};

createUser(mockDatabase, userId);

mockDatabase.allUsersRef.flush();
mockDatabase.activeUsersRef.flush();

expect(allUsersRef.getData()).toEqual(1);
expect(activeUsersRef.getData()).toEqual(1);
```

I envision an API that would put Database in charge of the data flow, allowing flushes and data-retrieval on database level. Such API which would enable the following testing scenario:

```
const mockDatabase = new MockFirebaseDatabase();

createUser(mockDatabase, userId);

mockDatabase.flush();

expect(mockDatabase.getData()).toEqual({
  users: {
    all: {
      [userId]: 1,
    },
    active: {
      [userId]: 1,
    }
  }
});
```

I raise this issue to measure the interest for this API change, and I would like to know if you'd welcome a PR that will introduce them. 

Side note:

The above example is contrived. The reality is that I'm passing a Database instance to a lot of functions, and I'm using atomic updates on a single reference where appropriate. Passing a root reference instead of a Database will be acceptable in most cases.

The example is there only to illustrate the difficulties which I will encounter if I wished to continue using Database as a dependency.

**Comment by soumak77** [comment]
You should create a mock firebase app which you can then use to inject into your application code.   For example:

```
var mockauth     = new firebasemock.MockFirebase();
var mockdatabase = new firebasemock.MockFirebase();
var mocksdk      = firebasemock.MockFirebaseSdk(function(path) {
  return path ? mockdatabase.child(path) : mockdatabase;
}, function() {
  return mockauth;
});
var mockapp     = mocksdk.initializeApp();
```

You can then test your function like so:
```
createUser(mockapp.database(), userId);

mockdatabase.flush();

expect(mockdatabase.getData()).toEqual({
  users: {
    all: {
      [userId]: 1,
    },
    active: {
      [userId]: 1,
    }
  }
});
```

**Comment by mpontus** [comment]
@soumak77 Thank you, this very helpful. Following your advice I was able to solve my issue with this simple test utility.

```
const MockFirebaseDatabase = data => {
  const rootRef = new firebasemock.MockFirebase(null, data);

  return {
    ref: path => rootRef.child(path),
    refFromUrl: url => rootRef.child(url),
    getData: () => rootRef.getData(),
    flush: () => rootRef.flush(),
  }
}
```

Do you think it would be sensible to change the behavior of MockFirebaseSdk to allow the following scenario?

```
const firebase = firebasemock.MockFirebaseSdk();

firebase.database().ref('/foo').set(1);
firebase.database().ref('/bar').set(2);
firebase.database().ref('/').flush();

expect(firebase.database.ref('/').getData()).toEqual({
  foo: 1,
  bar: 2,
});
```

**Comment by soumak77** [comment]
Your test code is broken.  By not providing the first argument to the method `MockFirebaseSdk`, a new mock database will be created each time you call `firebase.database()`.  Take a look at my example again and notice how I am passing a function as the first argument which then returns a reference to my existing mock database.  This ensures that all operations performed occur within the same mock database.

**Comment by mpontus** [comment]
Sorry for the confusion, @soumak77. Disregard the second snippet. 

Your solution works well for me. Thanks for all your help.
