### ISSUE TITLE
Use of orderByKey().startAt('desiredKey') always returns empty snapshot 

### ISSUE THREAD

**Issue by lewchuk-inkling** [soumak77/firebase-mock#56]
Queries support `limitToFirst` but not `startAt`. Example:

```js
var firebasemock  = require('firebase-mock');

var mockdatabase  = new firebasemock.MockFirebase();
var mockauth      = new firebasemock.MockFirebase();
var mocksdk       = firebasemock.MockFirebaseSdk(function(path) {
  return mockdatabase.child(path);
}, function() {
  return mockauth;
});

var ref = mocksdk.database().ref('data');
ref.child('key1').set('value1');
ref.child('key2').set('value2');
ref.child('key3').set('value3');
mockdatabase.flush();

function runQuery(query) {
	query.once('value').then(snapshot => {
		console.log(snapshot.numChildren());
		snapshot.forEach((childSnapshot) => {
			console.log(childSnapshot.key);
		});
	});
	mockdatabase.flush();
}

runQuery(ref.orderByKey().limitToFirst(2));
runQuery(ref.orderByKey().startAt('key2').limitToFirst(2));
```

Output:
```
2
key1
key2
0
```

Expected Output:
```
2
key1
key2
2
key2
key3
```

**Comment by soumak77** [comment]
See more here: https://github.com/soumak77/firebase-mock/blob/master/tutorials/rtdb/spies.md

**Comment by lewchuk-inkling** [comment]
@soumak77 sorry for the delay, I've added a description in case others end up here. The tutorials make it appear that none of the querying behaviour is expected to work. I was surprised because it looked like it worked in the first case but then didn't do what I expected in the second. If the expectation is that the library will not support these queries if it makes sense to log a warning or error if a query is executed?

**Comment by soumak77** [comment]
@lewchuk-inkling logging a warning would be a good idea
