### ISSUE TITLE
Unexpected error when installing through yarn

### ISSUE THREAD

**Issue by prescottprue** [soumak77/firebase-mock#61]
First off, thanks for the library. It is great to have this all wrapped up in one place.

Recently I started getting an error when installing through yarn:

```bash
An unexpected error occurred: "Couldn't find package \"lodash@^3.10.1\" required by \"firebase-mock@^2.1.0\" on the \"npm\" registry.".
```

Its weird though since lodash does have a 3.10.1 (confirmed through `npm view lodash`). It shouldn't matter, but I have another version of lodash already installed (`4.17.5`) in that project.

While we talking about lodash I had few questions:
* Is there a reason that lodash 3.10.1 is still being used?
* Are you open to looking into module lodash (either through slash requires or babel + plugin)? It could help reduce size quite a bit
* What are your thoughts on setting up babel? Some things could then be native JS over libraries. Totally open to helping - I saw #50 was about native promises, it would be pretty easy to capture both at once

**Comment by soumak77** [comment]
There is no specific reason the library is still using lodash 3.10.1.  I'm happy to accept a PR to upgrade to use only the lodash modules required by the code.

I'm also happy to accept any other PRs to update the codebase to ES6 and use babel for transpiling to ES5.

**Comment by soumak77** [comment]
@prescottprue I've updated the code to support lodash 4.17.5.  Please see if v2.1.3 fixes this issue.

**Comment by prescottprue** [comment]
Fixes the issue and works great, thanks!

Just as a note: we could still use `lodash` as a dependency (instead of each child dep) and just require them in a way that pulls that function instead of the whole lirbary i.e.:

```js
const get = require('lodash/get')
```

**Comment by soumak77** [comment]
@prescottprue yeah I know.  I probably should have just done that since the full `lodash` library is downloaded by multiple dependencies.  In any case, it's better for the long run to only download what is needed in case those libraries ever update to do the same.
