### ISSUE TITLE
When set is called with object with numeric keys, get returns an array

### ISSUE THREAD

**Issue by nonplus** [soumak77/firebase-mock#68]
Calling `set` with an object with **numeric keys**, causes `.once('value')` to return an array:
```typescript
  const obj = { 1: "foo", 2: "bar" }
  await database.ref("expenses").set(obj);
  const snapshot = await database.ref("expenses").once("value");
  console.log("snapshot.val()", snapshot.val());
```
Output:
```
snapshot.val() [ undefined, 'foo', 'bar' ]
```
If the object has at least **one non-numeric key**, it is correctly returned.

**Comment by soumak77** [comment]
This behavior was added with https://github.com/soumak77/firebase-mock/pull/37

@nonplus does firebase return the object or an array?

**Comment by nonplus** [comment]
OMG, that _is_ the behavior that you also get from Firebase. 🤢 

Well, that's pretty messed up, IMO, but firebase-mock behaves consistently.

Sorry about opening the issue.
