### ISSUE TITLE
The module md5 is not present when installing firebase-mock

### ISSUE THREAD

**Issue by alexjpaz** [soumak77/firebase-mock#69]
### The symptom

When attempting to require `firebase-mock` auth or bundling `firebase-mock` with a webpack 

```
./node_modules/firebase-mock/src/login.js
Module not found: `/Users/apaz/code/github.com/alexjpaz/liftit/packages/web/node_modules/md5/md5.js` does not match the corresponding path on disk `MD5`.
```

This seems to affect the build when using `yarn` or `npm`. I can confirm that the module `md5` is not present (however `md5.js` is).

### Workaround

Manually running `npm --save-dev md5` seems to resolve the issue.

### yarn.lock snippet

```
md5.js@^1.3.4:
  version "1.3.4"
  resolved "https://registry.yarnpkg.com/md5.js/-/md5.js-1.3.4.tgz#e9bdbde94a20a5ac18b04340fc5764d5b09d901d"
  dependencies:
    hash-base "^3.0.0"
    inherits "^2.0.1"

md5@^2.2.1:
  version "2.2.1"
  resolved "https://registry.yarnpkg.com/md5/-/md5-2.2.1.tgz#53ab38d5fe3c8891ba465329ea23fac0540126f9"
  dependencies:
    charenc "~0.0.1"
    crypt "~0.0.1"
    is-buffer "~1.1.1"
```

**Comment by soumak77** [comment]
@alexjpaz looks like `md5` isn't even really used.  I'll remove the module and publish a new patch release.
