### ISSUE TITLE
Support DocumentReference.create

### ISSUE THREAD

**Issue by starhoshi** [soumak77/firebase-mock#77]
Firestore.DocumentReference has `create` method.
Please support `create`.

https://github.com/googleapis/nodejs-firestore/blob/master/types/firestore.d.ts#L453-L460

**Comment by soumak77** [comment]
@starhoshi is `create` just an alias for `set` without any options?

**Comment by soumak77** [comment]
**create**: The write fails if the document already exists
**set**: The write will replace (or merge with) the existing document

**Comment by soumak77** [comment]
Implemented via #90
