### ISSUE TITLE
Changes to nested collections aren't reflected by queries to outer references

### ISSUE THREAD

**Issue by fshe** [soumak77/firebase-mock#79]
Hello, I am using this library with Jest to perform some testing. This is an example of what I am trying to do:
```javascript
it('Does not reflect changes to nested collections', async () => {
    const INITIAL_DB = {
      example: {
        collection1: {
          doc1: {
            collection2: {
              doc1: {
                prop1: 1,
              },
            },
          },
        },
      },
    };

    const mockfirestore = new FirebaseMock.MockFirestore();
    mockfirestore.autoFlush();

    const examplesRef = mockfirestore.collection('examples');
    examplesRef._setData(INITIAL_DB);

    // Change some data
    await examplesRef
      .doc('example')
      .collection('collection1')
      .doc('doc1')
      .collection('collection2')
      .doc('doc2')
      .set({ prop2: 2 });

    const noData = await examplesRef
      .doc('example')
      .collection('collection1')
      .getData();
    expect(noData).toMatchSnapshot();

    const hasData = await examplesRef
      .doc('example')
      .collection('collection1')
      .doc('doc1')
      .collection('collection2')
      .getData();
    expect(hasData).toMatchSnapshot();
  });
```
Here is the snapshot generated:
```

exports[`Does not reflect changes to nested collections 1`] = `
Object {
  "doc1": Object {
    "collection2": Object {
      "doc1": Object {
        "prop1": 1,
      },
    },
  },
}
`;

exports[`Does not reflect changes to nested collections 2`] = `
Object {
  "doc1": Object {
    "prop1": 1,
  },
  "doc2": Object {
    "prop2": 2,
  },
}
`;
```

As you can see,  the changes weren't visible unless I queried for the innermost collection. Is this the expected behavior? If so, could I get some guidance into how this is supposed to be done? Thank you!

**Comment by soumak77** [comment]
First off, I would suggest to not use any methods internal to `firebase-mock` (i.e. those starting with an underscore or even `getData()`).  Instead use the API provided by firebase to do anything.  This will help to remove any confusion as to what `firebase-mock` is doing internally, as from the test case perspective the functionality should be the exact same as the firebase API.

Second, there is no way to currently initialize the entire firestore database.  Instead you will need to perform the same API calls as you would in firebase to set the data.  Specifically:

```
const examplesRef = mockfirestore.collection('examples');
examplesRef.doc('example').collection('collection1').doc('doc1').collection('collection2').doc('doc1').set({
  prop1: 1
});
```
OR
```
mockfirestore.doc('examples/collection1/doc1/collection2/doc1').set({
  prop1: 1
});
```

Lastly, don't use `getData()`.  Instead you should call the firebase `get()` API and use the returned snapshot to inspect your data.

**Comment by fshe** [comment]
@soumak77 Thank you for the prompt response! I have edited the example as you suggested, there seems to still be an error. I believe the query to the outer document should reflect the changes to the inner document. :/ Please let me know if I have done something incorrect again!
```javascript
  it('Cannot query outer collection/doc for changes to inner collection', async () => {
    const mockfirestore = new FirebaseMock.MockFirestore();
    mockfirestore.autoFlush();

    // Initialize Firestore
    const examplesRef = mockfirestore.collection('examples');
    examplesRef.doc('example').collection('collection1').doc('doc1').collection('collection2').doc('doc1').set({
      prop1: 1,
    });

    const outerDocRef = examplesRef.doc('example').collection('collection1').doc('doc1');
    const noData = await outerDocRef.get();
    expect(noData.data()).toMatchSnapshot();

    const innerDocRef = outerDocRef.collection('collection2').doc('doc1');
    const hasData = await innerDocRef.get();
    expect(hasData.data()).toMatchSnapshot();
  });
```
Snapshot:
```
exports[`update-recent-activity Cannot query outer collection/doc for changes to inner collection 1`] = `null`;

exports[`update-recent-activity Cannot query outer collection/doc for changes to inner collection 2`] = `
Object {
  "prop1": 1,
}
`;

```

**Comment by soumak77** [comment]
@fshe I believe your confusion is due to the differences between realtime database and firestore.  Please familiarize yourself with the differences: https://firebase.google.com/docs/database/rtdb-vs-firestore

In terms of your specific example, when you query data for a specific document in firestore, you do not get data stored in child collections.  You will only get the data stored in the specific document at the location you are querying.

**Comment by fshe** [comment]
Aha! That makes sense to me. I appreciate you taking the time clear up my confusion. 🥇
