### ISSUE TITLE
Is there ever a use case when you'd purposefully import FirebaseMock without actually overriding?

### ISSUE THREAD

**Issue by mrozbarry** [soumak77/firebase-mock#9]
In short, I think it's hard to unintentionally import FirebaseMock (or any library) outside of your test environment, and I'd make a recommendation to make the behaviour always override on import.

Is that reasonable? Is there a use case I'm not thinking about where production code would include both FirebaseMock and Firebase?

**Comment by soumak77** [comment]
@mrozbarry your production code should never use FirebaseMock.  

A philosophy of unit testing is that each unit test should restore the environment back to its original state once completed (pass or fail).  While you can import FirebaseMock for all tests, it is likely that not every single test needs the mock imported.  So while the practice of overriding/restoring is repetitive, it is a best practice in unit testing.

If you wish you can choose to have your "original state" have the mocks included.  I don't think every user would want this functionality, so I'll leave the implementation as is.
