### ISSUE TITLE
batch.create not implemented

### ISSUE THREAD

**Issue by Rotorsoft** [soumak77/firebase-mock#99]
I'm currently overloading the entire batch, but should be as simple as below. This feature is needed to catch concurrency exceptions when using firestore to record events in event sourcing implementations.

mockfirestore.batch = function () {
  var self = this
  return {
    **create: function(doc, data) {
      if (doc.data) 
        throw Error('document already exists')
      doc.set(data)
    },**
    set: function(doc, data, opts) {
      var _opts = _.assign({}, { merge: false }, opts)
      if (_opts.merge) {
        doc._update(data, { setMerge: true });
      }
      else {
        doc.set(data)
      }
    },
    update: function(doc, data) {
      doc.update(data)
    },
    delete: function(doc) {
      doc.delete()
    },
    commit: function() {
      if (self.queue.events.length > 0) {
        self.flush()
      }
      return Promise.resolve()
    }
  }
}

**Comment by Rotorsoft** [comment]
Hi soumak77,
Are you still supporting this project? This is the most complete firebase mock library out there and would be a shame if some of the basic capabilities are missed. I'm currently patching "create" to be able to complete my tests (see below), but would prefer if you or some other contributor makes it official considering your global understanding of this product.
Cheers!

```javascript
const doccreate = function (data, callback) {
  var err = this._nextErr('create');
  if (this.data) 
    err = new Error('document already exists')
  else 
    data = _.cloneDeep(data);
  var self = this;
  return new Promise(function (resolve, reject) {
    self._defer('create', _.toArray(arguments), function () {
      if (err === null) {
        self._dataChanged(data);
        resolve(data);
      } else {
        if (callback) {
          callback(err);
        }
        reject(err);
      }
    });
  });
};

firebasemock.MockFirestore.prototype.batch = function () {
  var self = this;
  let promises = []
  return {
    create: function(doc, data) {
      Object.getPrototypeOf(doc).create = doccreate
      promises.push(doc.create(data))
    }, 
    set: function(doc, data, opts) {
      var _opts = _.assign({}, { merge: false }, opts);
      if (_opts.merge) {
        promises.push(doc._update(data, { setMerge: true }))
      }
      else {
        promises.push(doc.set(data))
      }
    },
    update: function(doc, data) {
      promises.push(doc.update(data))
    },
    delete: function(doc) {
      promises.push(doc.delete())
    },
    commit: function() {
      if (self.queue.events.length > 0) {
        self.flush();
      }
      // execute sequentially
      return Promise.all(promises)
      // return promises.reduce((chain, task) => { 
      //   return chain.then(results => task.then(result => [...results, result]))
      // }, Promise.resolve([]))
    }
  };
};
```

**Comment by soumak77** [comment]
@Rotorsoft yes this library is still supported, however, I need help from the community to help implement missing APIs.  PR #90 implemented doc.create, so a new PR can be submitted which adds batch.create.

**Comment by soumak77** [comment]
It looks as those this method has been added.  Please reopen if you are still haven't trouble using `batch.create`

https://github.com/soumak77/firebase-mock/blob/040a4929d11cce4a27e62391d539fb67d3963cef/src/firestore.js#L117-L120
